"""MVP 15 — install extended biome backgrounds + active spot props from staging PNGs."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'public/assets/minigames/myrion-worksite'
STAGING = ROOT / 'staging/myrion-worksite-mvp15/generated'
REGISTRY = ROOT / 'src/data/myrionWorksiteAssetRegistry.ts'
MANIFEST = ROOT / 'staging/manifests/myrion-worksite-mvp15.json'

WIDE_W, WIDE_H = 2560, 960
MIN_BG_W, MIN_BG_H = 1920, 720
SPOT_CANVAS = 1024
MIN_SPOT = 512
WHITE_THRESH = 245


@dataclass
class AssetResult:
    rel_path: str
    ok: bool
    reason: str
    size: tuple[int, int] | None = None


def is_generated_bg(r: int, g: int, b: int) -> bool:
    if r >= WHITE_THRESH and g >= WHITE_THRESH and b >= WHITE_THRESH:
        return True
    if r <= 28 and g <= 28 and b <= 28:
        return True
    lum = (r + g + b) / 3
    chroma = max(r, g, b) - min(r, g, b)
    if chroma <= 18:
        if 108 <= lum <= 138 or 178 <= lum <= 208:
            return True
    return False


def remove_generated_bg(im: Image.Image) -> Image.Image:
    im = im.convert('RGBA')
    pixels = list(im.getdata())
    new_pixels: list[tuple[int, int, int, int]] = []
    for r, g, b, a in pixels:
        if is_generated_bg(r, g, b):
            new_pixels.append((r, g, b, 0))
        else:
            new_pixels.append((r, g, b, a))
    im.putdata(new_pixels)
    return im


def to_wide_panoramic(src: Path, dest: Path) -> tuple[int, int]:
    im = Image.open(src).convert('RGB')
    scale = max(WIDE_W / im.width, WIDE_H / im.height)
    nw, nh = int(im.width * scale), int(im.height * scale)
    im = im.resize((nw, nh), Image.Resampling.LANCZOS)
    left = (nw - WIDE_W) // 2
    top = (nh - WIDE_H) // 2
    out = im.crop((left, top, left + WIDE_W, top + WIDE_H))
    dest.parent.mkdir(parents=True, exist_ok=True)
    out.save(dest, optimize=True)
    return out.size


def to_spot_icon(src: Path, dest: Path) -> tuple[tuple[int, int], float]:
    im = remove_generated_bg(Image.open(src))
    bbox = im.getbbox()
    if not bbox:
        raise RuntimeError(f'empty spot after bg removal: {src}')
    im = im.crop(bbox)
    max_side = int(SPOT_CANVAS * 0.82)
    im.thumbnail((max_side, max_side), Image.Resampling.LANCZOS)
    if im.width < MIN_SPOT // 2 or im.height < MIN_SPOT // 2:
        raise RuntimeError(f'spot too small after crop: {src}')
    out = Image.new('RGBA', (SPOT_CANVAS, SPOT_CANVAS), (0, 0, 0, 0))
    x = (SPOT_CANVAS - im.width) // 2
    y = (SPOT_CANVAS - im.height) // 2
    out.paste(im, (x, y), im)
    dest.parent.mkdir(parents=True, exist_ok=True)
    out.save(dest, optimize=True)
    alpha = out.split()[-1]
    opaque = sum(1 for v in alpha.getdata() if v > 200)
    ratio = opaque / (SPOT_CANVAS * SPOT_CANVAS)
    return out.size, ratio


def validate_background(path: Path) -> AssetResult:
    rel = path.relative_to(BASE).as_posix()
    try:
        im = Image.open(path)
        w, h = im.size
        if w < MIN_BG_W or h < MIN_BG_H:
            return AssetResult(rel, False, f'too_small({w}x{h})', (w, h))
        rgb = im.convert('RGB')
        pixels = list(rgb.getdata())
        white = sum(1 for r, g, b in pixels if r >= WHITE_THRESH and g >= WHITE_THRESH and b >= WHITE_THRESH)
        if white / max(len(pixels), 1) > 0.55:
            return AssetResult(rel, False, 'mostly_white', (w, h))
        return AssetResult(rel, True, 'ok', (w, h))
    except Exception as exc:  # noqa: BLE001
        return AssetResult(rel, False, str(exc))


def validate_spot(path: Path) -> AssetResult:
    rel = path.relative_to(BASE).as_posix()
    try:
        im = Image.open(path).convert('RGBA')
        w, h = im.size
        if w < MIN_SPOT or h < MIN_SPOT:
            return AssetResult(rel, False, f'too_small({w}x{h})', (w, h))
        alpha = im.split()[-1]
        data = list(alpha.getdata())
        transparent = sum(1 for v in data if v < 16)
        opaque = sum(1 for v in data if v > 200)
        total = len(data)
        if transparent / total < 0.08:
            return AssetResult(rel, False, 'low_transparency', (w, h))
        if opaque / total < 0.04:
            return AssetResult(rel, False, 'mostly_transparent', (w, h))
        return AssetResult(rel, True, 'ok', (w, h))
    except Exception as exc:  # noqa: BLE001
        return AssetResult(rel, False, str(exc))


def write_registry(available: list[str], rejected: dict[str, str]) -> None:
    lines = [
        '/** Auto-generated by scripts/mvp15-install-worksite-assets.py — do not edit by hand. */',
        '',
        '/** Chemins relatifs à public/assets/minigames/myrion-worksite/ */',
        'export const WORKSITE_MVP15_AVAILABLE_ASSETS = new Set<string>([',
    ]
    for path in sorted(available):
        lines.append(f"  '{path}',")
    lines.append('])')
    lines.append('')
    lines.append('export const WORKSITE_MVP15_REJECTED_ASSETS: Record<string, string> = {')
    for path, reason in sorted(rejected.items()):
        safe = reason.replace("'", "\\'")
        lines.append(f"  '{path}': '{safe}',")
    lines.append('}')
    lines.append('')
    lines.append('export function isWorksiteAssetAvailable(relPath: string): boolean {')
    lines.append('  return WORKSITE_MVP15_AVAILABLE_ASSETS.has(relPath)')
    lines.append('}')
    lines.append('')
    REGISTRY.write_text('\n'.join(lines), encoding='utf-8')


def install_from_staging() -> tuple[list[AssetResult], list[AssetResult]]:
    if not MANIFEST.exists():
        raise SystemExit(f'Missing manifest: {MANIFEST}')
    manifest = json.loads(MANIFEST.read_text(encoding='utf-8'))
    bg_results: list[AssetResult] = []
    spot_results: list[AssetResult] = []

    for entry in manifest.get('backgrounds', []):
        staging_name = entry['staging']
        out_name = entry['output']
        src = STAGING / staging_name
        dest = BASE / 'backgrounds' / out_name
        if not src.exists():
            bg_results.append(AssetResult(f'backgrounds/{out_name}', False, 'missing_staging'))
            continue
        try:
            size = to_wide_panoramic(src, dest)
            result = validate_background(dest)
            result.size = size
            bg_results.append(result)
            print(f"background {out_name}: {size[0]}x{size[1]} -> {result.reason}")
        except Exception as exc:  # noqa: BLE001
            bg_results.append(AssetResult(f'backgrounds/{out_name}', False, str(exc)))

    for entry in manifest.get('spots', []):
        staging_name = entry['staging']
        out_name = entry['output']
        src = STAGING / staging_name
        dest = BASE / 'spots' / out_name
        if not src.exists():
            spot_results.append(AssetResult(f'spots/{out_name}', False, 'missing_staging'))
            continue
        try:
            size, opaque = to_spot_icon(src, dest)
            result = validate_spot(dest)
            result.size = size
            if opaque > 0.72:
                result.ok = False
                result.reason = f'too_opaque({opaque:.1%})'
            spot_results.append(result)
            print(f"spot {out_name}: {size[0]}x{size[1]} opaque={opaque:.1%} -> {result.reason}")
        except Exception as exc:  # noqa: BLE001
            spot_results.append(AssetResult(f'spots/{out_name}', False, str(exc)))

    return bg_results, spot_results


def scan_existing() -> tuple[list[str], dict[str, str]]:
    """Validate already-installed MVP assets (core biomes + legacy spots)."""
    available: list[str] = []
    rejected: dict[str, str] = {}

    core_backgrounds = ['prairie.png', 'forest.png', 'mine.png']
    for name in core_backgrounds:
        path = BASE / 'backgrounds' / name
        if path.exists():
            result = validate_background(path)
            if result.ok:
                available.append(result.rel_path)
            else:
                rejected[result.rel_path] = result.reason

    core_spots = [
        'bosquet.png', 'pierrier.png', 'champs.png',
        'sous-bois.png', 'clairiere-herbes.png', 'source-claire.png',
        'pierrier-profond.png', 'veine-brute.png', 'charbonniere.png',
        'faille-astrale.png',
    ]
    for name in core_spots:
        path = BASE / 'spots' / name
        if path.exists():
            result = validate_spot(path)
            if result.ok:
                available.append(result.rel_path)
            else:
                rejected[result.rel_path] = result.reason

    return available, rejected


def main() -> None:
    STAGING.mkdir(parents=True, exist_ok=True)
    available, rejected = scan_existing()
    bg_results, spot_results = install_from_staging()

    for result in [*bg_results, *spot_results]:
        if result.ok:
            available.append(result.rel_path)
        else:
            rejected[result.rel_path] = result.reason

    available = sorted(set(available))
    write_registry(available, rejected)

    ok_count = len(available)
    reject_count = len(rejected)
    print(f'\nRegistry: {ok_count} available, {reject_count} rejected')
    print(f'Wrote {REGISTRY.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
