/* Auto-generated by scripts/import-myrions-assets.mjs — do not edit by hand. */

export const MYRIONS_BIOMES = [
  {
    "id": "prairie-solaire",
    "name": "Prairie solaire",
    "emoji": "☀️",
    "fallbackGradient": "linear-gradient(180deg, #fff8d8 0%, #ffe08a 40%, #9ed56b 100%)"
  },
  {
    "id": "foret-ancienne",
    "name": "Forêt ancienne",
    "emoji": "🌲",
    "fallbackGradient": "linear-gradient(180deg, #1a3020 0%, #4a7850 45%, #2a5038 100%)"
  },
  {
    "id": "marais-brumeux",
    "name": "Marais brumeux",
    "emoji": "🌫️",
    "fallbackGradient": "linear-gradient(180deg, #243038 0%, #5a7878 45%, #3a5848 100%)"
  },
  {
    "id": "montagnes-cristallines",
    "name": "Montagnes cristallines",
    "emoji": "💎",
    "fallbackGradient": "linear-gradient(180deg, #1a2848 0%, #7ec8ff 50%, #e8f8ff 100%)"
  },
  {
    "id": "desert-rouge",
    "name": "Désert rouge",
    "emoji": "🏜️",
    "fallbackGradient": "linear-gradient(180deg, #3a1820 0%, #d06030 55%, #ffb86b 100%)"
  },
  {
    "id": "rivage-corallien",
    "name": "Rivage corallien",
    "emoji": "🐚",
    "fallbackGradient": "linear-gradient(180deg, #1a2848 0%, #4a98c8 55%, #ffd9a8 100%)"
  },
  {
    "id": "volcan-noir",
    "name": "Volcan noir",
    "emoji": "🌋",
    "fallbackGradient": "linear-gradient(180deg, #120810 0%, #602028 50%, #ff7040 100%)"
  },
  {
    "id": "ruines-astrales",
    "name": "Ruines astrales",
    "emoji": "✨",
    "fallbackGradient": "linear-gradient(180deg, #181028 0%, #5848a8 50%, #ffd56a 100%)"
  }
] as const

export const MYRIONS_SPECIES = [
  {
    "id": "equilux",
    "name": "Équilux, Gardien de l'Aube",
    "emoji": "☀️",
    "rarity": "LR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "cerfaurore",
    "name": "Cerfaurore",
    "emoji": "☀️",
    "rarity": "SSR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "treflaon",
    "name": "Trèflaon",
    "emoji": "☀️",
    "rarity": "SR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "bourdilune",
    "name": "Bourdilune",
    "emoji": "☀️",
    "rarity": "N",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "mielpique",
    "name": "Mielpique",
    "emoji": "☀️",
    "rarity": "SR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "moussprout",
    "name": "Moussprout",
    "emoji": "☀️",
    "rarity": "N",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "aubepineon",
    "name": "Aubépineon",
    "emoji": "☀️",
    "rarity": "SSR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "rosalynx",
    "name": "Rosalynx",
    "emoji": "☀️",
    "rarity": "SSR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "solhermine",
    "name": "Solhermine",
    "emoji": "☀️",
    "rarity": "SR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "solarcheval",
    "name": "Solarcheval",
    "emoji": "☀️",
    "rarity": "UR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "floracroc",
    "name": "Floracroc",
    "emoji": "☀️",
    "rarity": "SR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "paladigrain",
    "name": "Paladigrain",
    "emoji": "☀️",
    "rarity": "UR",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "florelievre",
    "name": "Florelièvre",
    "emoji": "☀️",
    "rarity": "N",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "grainocorne",
    "name": "Grainocorne",
    "emoji": "☀️",
    "rarity": "N",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "pepitouffe",
    "name": "Pépitouffe",
    "emoji": "☀️",
    "rarity": "N",
    "biomeId": "prairie-solaire"
  },
  {
    "id": "brindhibou",
    "name": "Brindhibou",
    "emoji": "🌲",
    "rarity": "N",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "noisecureuil",
    "name": "Noisécureuil",
    "emoji": "🌲",
    "rarity": "N",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "fongours",
    "name": "Fongours",
    "emoji": "🌲",
    "rarity": "SR",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "limafleur",
    "name": "Limafleur",
    "emoji": "🌲",
    "rarity": "N",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "lianaconda",
    "name": "Lianaconda",
    "emoji": "🌲",
    "rarity": "SR",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "orvalis",
    "name": "Orvalis, Cœur de la Forêt",
    "emoji": "🌲",
    "rarity": "LR",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "sylvarat",
    "name": "Sylvarat",
    "emoji": "🌲",
    "rarity": "SR",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "luciferne",
    "name": "Luciferne",
    "emoji": "🌲",
    "rarity": "SR",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "champi-chaton",
    "name": "Champi-chaton",
    "emoji": "🌲",
    "rarity": "N",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "mouscarotte",
    "name": "Mouscarotte",
    "emoji": "🌲",
    "rarity": "N",
    "biomeId": "foret-ancienne"
  },
  {
    "id": "bourbecaille",
    "name": "Bourbécaille",
    "emoji": "🌫️",
    "rarity": "N",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "tourbapince",
    "name": "Tourbapince",
    "emoji": "🌫️",
    "rarity": "SR",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "vipervase",
    "name": "Vipervase",
    "emoji": "🌫️",
    "rarity": "SR",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "nebularve",
    "name": "Nébularve",
    "emoji": "🌫️",
    "rarity": "SR",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "glucrapaud",
    "name": "Glucrapaud",
    "emoji": "🌫️",
    "rarity": "N",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "croacendre",
    "name": "Croacendre",
    "emoji": "🌫️",
    "rarity": "SR",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "moustikroa",
    "name": "Moustikroa",
    "emoji": "🌫️",
    "rarity": "N",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "vasardille",
    "name": "Vasardille",
    "emoji": "🌫️",
    "rarity": "N",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "mirelith",
    "name": "Mirelith, Roi du Marais Sans Fond",
    "emoji": "🌫️",
    "rarity": "LR",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "nenuphant",
    "name": "Nénuphant",
    "emoji": "🌫️",
    "rarity": "N",
    "biomeId": "marais-brumeux"
  },
  {
    "id": "avalanchevre",
    "name": "Avalanchèvre",
    "emoji": "💎",
    "rarity": "SR",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "cailloubic",
    "name": "Cailloubic",
    "emoji": "💎",
    "rarity": "N",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "krysalor",
    "name": "Krysalor, Dragon des Cimes",
    "emoji": "💎",
    "rarity": "LR",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "pikroc",
    "name": "Pikroc",
    "emoji": "💎",
    "rarity": "N",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "glacimarmotte",
    "name": "Glacimarmotte",
    "emoji": "💎",
    "rarity": "SR",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "quartzard",
    "name": "Quartzard",
    "emoji": "💎",
    "rarity": "SR",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "rocorbeau",
    "name": "Rocorbeau",
    "emoji": "💎",
    "rarity": "SR",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "givrimoineau",
    "name": "Givrimoineau",
    "emoji": "💎",
    "rarity": "N",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "gemlimace",
    "name": "Gemlimace",
    "emoji": "💎",
    "rarity": "N",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "cristaloupin",
    "name": "Cristaloupin",
    "emoji": "💎",
    "rarity": "N",
    "biomeId": "montagnes-cristallines"
  },
  {
    "id": "dromaglyphe",
    "name": "Dromaglyphe",
    "emoji": "🏜️",
    "rarity": "SR",
    "biomeId": "desert-rouge"
  },
  {
    "id": "fenneflamme",
    "name": "Fenneflamme",
    "emoji": "🏜️",
    "rarity": "SR",
    "biomeId": "desert-rouge"
  },
  {
    "id": "amonraxis",
    "name": "Amonraxis, Mirage Royal",
    "emoji": "🏜️",
    "rarity": "LR",
    "biomeId": "desert-rouge"
  },
  {
    "id": "dunecaille",
    "name": "Dunécaille",
    "emoji": "🏜️",
    "rarity": "N",
    "biomeId": "desert-rouge"
  },
  {
    "id": "vautourune",
    "name": "Vautourune",
    "emoji": "🏜️",
    "rarity": "SR",
    "biomeId": "desert-rouge"
  },
  {
    "id": "mirajackal",
    "name": "Mirajackal",
    "emoji": "🏜️",
    "rarity": "N",
    "biomeId": "desert-rouge"
  },
  {
    "id": "sablitou",
    "name": "Sablitou",
    "emoji": "🏜️",
    "rarity": "N",
    "biomeId": "desert-rouge"
  },
  {
    "id": "cactouris",
    "name": "Cactouris",
    "emoji": "🏜️",
    "rarity": "N",
    "biomeId": "desert-rouge"
  },
  {
    "id": "scorpiquet",
    "name": "Scorpiquet",
    "emoji": "🏜️",
    "rarity": "N",
    "biomeId": "desert-rouge"
  },
  {
    "id": "cobrambre",
    "name": "Cobrambre",
    "emoji": "🏜️",
    "rarity": "SR",
    "biomeId": "desert-rouge"
  },
  {
    "id": "pincelot",
    "name": "Pincelot",
    "emoji": "🐚",
    "rarity": "N",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "coquichat",
    "name": "Coquichat",
    "emoji": "🐚",
    "rarity": "N",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "corailynx",
    "name": "Corailynx",
    "emoji": "🐚",
    "rarity": "SR",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "hippocampearl",
    "name": "Hippocampearl",
    "emoji": "🐚",
    "rarity": "SR",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "algouette",
    "name": "Algouette",
    "emoji": "🐚",
    "rarity": "N",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "thalassor",
    "name": "Thalassor, Seigneur du Lagon",
    "emoji": "🐚",
    "rarity": "LR",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "meduflore",
    "name": "Méduflore",
    "emoji": "🐚",
    "rarity": "SR",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "sablapin",
    "name": "Sablapin",
    "emoji": "🐚",
    "rarity": "N",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "bullorbe",
    "name": "Bullorbe",
    "emoji": "🐚",
    "rarity": "N",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "tortecume",
    "name": "Tortécume",
    "emoji": "🐚",
    "rarity": "SR",
    "biomeId": "rivage-corallien"
  },
  {
    "id": "charbouvier",
    "name": "Charbouvier",
    "emoji": "🌋",
    "rarity": "N",
    "biomeId": "volcan-noir"
  },
  {
    "id": "magmardillo",
    "name": "Magmardillo",
    "emoji": "🌋",
    "rarity": "SR",
    "biomeId": "volcan-noir"
  },
  {
    "id": "fumhibou",
    "name": "Fumhibou",
    "emoji": "🌋",
    "rarity": "SR",
    "biomeId": "volcan-noir"
  },
  {
    "id": "cendreloup",
    "name": "Cendreloup",
    "emoji": "🌋",
    "rarity": "SR",
    "biomeId": "volcan-noir"
  },
  {
    "id": "vulkarion",
    "name": "Vulkarion, Cœur du Volcan Noir",
    "emoji": "🌋",
    "rarity": "LR",
    "biomeId": "volcan-noir"
  },
  {
    "id": "lavacroa",
    "name": "Lavacroa",
    "emoji": "🌋",
    "rarity": "N",
    "biomeId": "volcan-noir"
  },
  {
    "id": "obsidigriffe",
    "name": "Obsidigriffe",
    "emoji": "🌋",
    "rarity": "N",
    "biomeId": "volcan-noir"
  },
  {
    "id": "cendroquet",
    "name": "Cendroquet",
    "emoji": "🌋",
    "rarity": "N",
    "biomeId": "volcan-noir"
  },
  {
    "id": "pyrocorne",
    "name": "Pyrocorne",
    "emoji": "🌋",
    "rarity": "SR",
    "biomeId": "volcan-noir"
  },
  {
    "id": "flamurmulot",
    "name": "Flamurmulot",
    "emoji": "🌋",
    "rarity": "N",
    "biomeId": "volcan-noir"
  },
  {
    "id": "asterion",
    "name": "Asterion, Gardien des Ruines Célestes",
    "emoji": "✨",
    "rarity": "LR",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "comechat",
    "name": "Coméchat",
    "emoji": "✨",
    "rarity": "N",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "orbicrabe",
    "name": "Orbicrabe",
    "emoji": "✨",
    "rarity": "SR",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "astromouche",
    "name": "Astromouche",
    "emoji": "✨",
    "rarity": "N",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "lunacorne",
    "name": "Lunacorne",
    "emoji": "✨",
    "rarity": "N",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "glyphibou",
    "name": "Glyphibou",
    "emoji": "✨",
    "rarity": "N",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "nebuloup",
    "name": "Nebuloup",
    "emoji": "✨",
    "rarity": "SR",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "stellapin",
    "name": "Stellapin",
    "emoji": "✨",
    "rarity": "N",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "selenard",
    "name": "Sélénard",
    "emoji": "✨",
    "rarity": "SR",
    "biomeId": "ruines-astrales"
  },
  {
    "id": "runescarab",
    "name": "Runescarab",
    "emoji": "✨",
    "rarity": "SR",
    "biomeId": "ruines-astrales"
  }
] as const

export const MYRIONS_BIOME_IDS = MYRIONS_BIOMES.map((biome) => biome.id)
